# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

defaults: &defaults
  working_directory: ~/project/ivi
  docker:
    - image: circleci/node:11

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ivi-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-ivi-{{ arch }}-{{ .Branch }}-
            - v1-ivi-{{ arch }}-
      - run: yarn install --pure-lockfile --non-interactive
      - save_cache:
          key: v1-ivi-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - ivi

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run tslint --project ./tsconfig.json

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run jest -w 1

  test-cover:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run jest -w 1 --coverage --coverageReporters=text-lcov > coverage.lcov
      - run:
         name: report coverage stats for non-PRs
         command: |
           if [[ -z $CI_PULL_REQUEST ]]; then
             yarn codecov
           fi

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - test-cover:
          requires:
            - install
